apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: skandude/webapp:imgtag
        name: nginx

---
apiVersion: v1
kind: Service
metadata:
    name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mydep
  ports:
  - port: 80
    nodePort: 30123
